#!/bin/bash

path=/sys/class/backlight/intel_backlight

MON=`xrandr | grep " connected" | cut -d ' ' -f 1`

luminance() {
    read -r level < "$path"/actual_brightness
    factor=$((max / 100))
    ret=`printf '%d\n' "$((level / factor))"`
    if [ $ret -gt 100 ]; then
       ret=100
    fi
    printf `echo "$ret / 100" | bc -l`
}

read -r max < "$path"/max_brightness

while inotifywait -e modify "$path"/actual_brightness; do
  lm=$(luminance)
  echo -n "${lm}" > ~/.brightness
  xrandr --output "${MON}" --brightness "${lm}"
done
