#!/bin/bash

#MON="eDP-1-1"    # Discover monitor name with: xrandr | grep " connected"
MON=`xrandr | grep " connected" | cut -d ' ' -f 1`

if [ "$#" -gt 0 ]; then
  xrandr --output "$MON" --brightness "$1"   # Set new brightness
fi

# Display current brightness
printf "Monitor $MON "
echo $( xrandr --verbose --current | grep ^"$MON" -A5 | tail -n1 )
